name: build container
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"
env:
  tag: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout action
      uses: actions/checkout@v4
    - name: build
      run: podman build -f Containerfile -t ${{ env.tag }} .
    - name: push
      run: podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} ${{ env.tag }}
